version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"

  node:
    build: ./utask/frontend
    volumes:
      - ./utask/frontend:/app/frontend
      - ./utask/frontend/node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

  django:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  node-modules:
