# Generated by Django 2.0.7 on 2018-07-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180723_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='wallet_id',
            new_name='ost_id',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='summary',
            new_name='description',
        ),
    ]
