# Generated by Django 2.0.7 on 2018-07-29 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_auto_20180728_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='completions',
        ),
        migrations.AddField(
            model_name='taskreward',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Task'),
        ),
        migrations.AddField(
            model_name='taskreward',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
