# Generated by Django 2.0.7 on 2018-08-05 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180729_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livetask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='live_tasks', to='api.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='total_cost',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='taskreward',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='completions', to='api.Task'),
        ),
    ]
